services:
  postgres_item:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=item_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'
